---
title: "R Notebook"
output: html_notebook
---

```{r}
library(rio)
library(tidyverse)
library(ggplot2)
library(ggsankey)
```


```{r}
a1 <- import("netflix.xlsx")
```

```{r}
df <- a1 %>%
  make_long(Category1, Category2, Category3, Amount)
```


```{r}
pl <- ggplot(df, aes(x = x
                     , next_x = next_x
                     , node = node
                     , next_node = next_node
                     , fill = factor(node)
                     , label = node)
             )
pl <- pl +geom_sankey(flow.alpha = 0.5
                      , node.color = "black"
                      ,show.legend = FALSE)
pl <- pl +geom_sankey_label(size = 3, color = "black", fill= "white", hjust = -0.5)
pl <- pl +  theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl +  theme(axis.title = element_blank()
                  , axis.text.y = element_blank()
                  , axis.ticks = element_blank()  
                  , panel.grid = element_blank())
pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = "The Economics of NETFLIX")
pl <- pl + labs(subtitle = "Using  David Sjoberg's ggsankey package")
pl <- pl + labs(caption = "@butames")
pl <- pl + labs(fill = 'Nodes')

```

```{r}
pl
```


```{r}
dagg <- df %>%
  group_by(node)%>%
  tally()

dagg2 <- df %>%
  group_by(next_x)%>%
  tally()

dagg3 <- df %>%
  group_by(next_node)%>%
  tally()

# Step 3
df2 <- merge(df, dagg2, by.x = 'next_x', by.y = 'next_x', all.x = TRUE)

```


```{r}
pl <- ggplot(df2, aes(x = x
                      , next_x = next_x
                      , node = node
                      , next_node = next_node
                      , fill = factor(node)
                      
                      , label = paste0(node," n=", n)
)
) 
pl <- pl +geom_sankey(flow.alpha = 0.5,  color = "gray40", show.legend = TRUE)
pl <- pl +geom_sankey_label(size = 3, color = "white", fill= "gray40", hjust = -0.2)

pl <- pl +  theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl +  theme(axis.title = element_blank()
                  , axis.text.y = element_blank()
                  , axis.ticks = element_blank()  
                  , panel.grid = element_blank())
pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = "Sankey diagram using ggplot")
pl <- pl + labs(subtitle = "using  David Sjoberg's ggsankey package")
pl <- pl + labs(caption = "@techanswers88")
pl <- pl + labs(fill = 'Nodes')
```

```{r}
b1 <- a1 %>%
  data.frame(a1) %>%
  mutate_at(c("Category2", "Category3"), as.factor)

is_alluvia_form(as.data.frame(a1), axes = 1:3, silent = TRUE)

```


```{r}
ggplot(as.data.frame(b1),
       aes(y = Amount, axis1 = Category2, axis2 = Category3)) +
  geom_alluvium(aes(fill = factor(Amount)), width = 1/12) +
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Category2", "Category3"), expand = c(.05, .05)) +
  scale_fill_brewer(type = "qual", palette = "Set1") +
  ggtitle("UC Berkeley admissions and rejections, by sex and department")
```

